Update docs
vvorld/getid-web-sdk pull request #139
Opened 2021-02-16 08:39 UTC by rexemtoxa

2021-02-17 17:13 UTC, lukesolo requested changes

2021-02-17 17:13 UTC, lukesolo commented on README.md
> +In case when you not specify the Form field but specify this data into profile, this data will send from web sdk to the server and will participate in cross-checking
Form fields and pre-filled fields will be sent to the server and will be compared with extracted data from a document.

2021-02-17 17:13 UTC, lukesolo commented on README.md
> +We provide cross-checking comparison by next Form fields:
Profile checking is provided for those fields:

2021-02-17 17:13 UTC, lukesolo commented on README.md
> +It is possible to customize the styles by two way:
ways

2021-02-17 17:13 UTC, lukesolo commented on README.md
> +- By insert the custom css as string
inserting the custom CSS string

2021-02-17 17:13 UTC, lukesolo commented on README.md
> +- By CSS Variables
using CSS variables

2021-02-17 17:13 UTC, lukesolo commented on README.md
> +To insert the custom css just specify filed *injectCSS* into config with a css string as a value
Example of custom CSS string:

2021-02-17 17:13 UTC, lukesolo commented on README.md
> +  flowName: 'yourFlowName',
CAPS_CASE

2021-02-17 17:13 UTC, lukesolo commented on README.md
> +The using custom variables it's the more flexible and convenient way
Custom variables is a more flexible and convenient way. List of variables:

2021-02-17 17:13 UTC, lukesolo commented on README.md
> +to customize style specify this variables for element with next id: getid-main, getid-popup__main
Use these element ids (`getid-main`, `getid-popup__main`) to customize style using variables

2021-02-18 09:23 UTC, rexemtoxa commented on README.md
>  #### Including the library
done

2021-02-18 09:23 UTC, rexemtoxa commented on README.md
> +- NPM launcher
done

2021-02-18 09:25 UTC, rexemtoxa commented on README.md
> +config example for authorization by sdkKey:
done

2021-02-18 09:26 UTC, rexemtoxa commented on README.md
> +configuration example with authorization by JWT
done

2021-02-18 09:27 UTC, rexemtoxa commented on README.md
> +    'Access-Control-Allow-Origin': '*',
done

2021-02-19 09:43 UTC, merged